version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    expose:
      - 2181
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.15.11
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper

  producer3:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PRODUCER_GROUP_ID: producer3
    volumes:
      - ./:/my_app
    command: bash -c "./wait-for-it.sh -t 300 kafka:9092 && python producer.py"
    depends_on:
      - kafka

  producer2:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PRODUCER_GROUP_ID: producer2
    volumes:
      - ./:/my_app
    command: bash -c "./wait-for-it.sh -t 300 kafka:9092 && python producer.py"
    depends_on:
      - kafka

  producer1:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PRODUCER_GROUP_ID: producer1
    volumes:
      - ./:/my_app
    command: bash -c "./wait-for-it.sh -t 300 kafka:9092 && python producer.py"
    depends_on:
      - kafka

  consumer:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      CONSUMER_GROUP_ID: consumer1
    volumes:
      - ./:/my_app
    command: bash -c "./wait-for-it.sh -t 300 kafka:9092 && python consumer.py"
    depends_on:
      - kafka
